-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 08:14:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema unisphere
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unisphere
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unisphere` DEFAULT CHARACTER SET utf8mb3 ;
USE `unisphere` ;

-- -----------------------------------------------------
-- Table `unisphere`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisphere`.`posts` (
  `idposts` INT NOT NULL AUTO_INCREMENT,
  `posts` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idposts`),
  UNIQUE INDEX `idposts_UNIQUE` (`idposts` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `unisphere`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisphere`.`replies` (
  `idreplies` INT NOT NULL,
  `replies` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idreplies`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `unisphere`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisphere`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `DisplayName` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `unisphere`.`repliesuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisphere`.`repliesuser` (
  `id` INT NOT NULL,
  `ReplyID` INT NOT NULL,
  `PostID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `ReplyID_UNIQUE` (`ReplyID` ASC) VISIBLE,
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  INDEX `PostsID_idx` (`PostID` ASC) VISIBLE,
  CONSTRAINT `PostsID`
    FOREIGN KEY (`PostID`)
    REFERENCES `unisphere`.`posts` (`idposts`),
  CONSTRAINT `RepliesID`
    FOREIGN KEY (`ReplyID`)
    REFERENCES `unisphere`.`replies` (`idreplies`),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `unisphere`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `unisphere`.`userposts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unisphere`.`userposts` (
  `id` INT NOT NULL,
  `PostsID` INT NOT NULL,
  `UsersID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `PostsID_UNIQUE` (`PostsID` ASC) VISIBLE,
  UNIQUE INDEX `UsersID_UNIQUE` (`UsersID` ASC) VISIBLE,
  CONSTRAINT `postid`
    FOREIGN KEY (`PostsID`)
    REFERENCES `unisphere`.`posts` (`idposts`),
  CONSTRAINT `UsersID`
    FOREIGN KEY (`UsersID`)
    REFERENCES `unisphere`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
